<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\logo.png" />
    <Resource Include="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
  </ItemGroup>

</Project>
